# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-16 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20200216_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institude',
            name='institude_id',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=7),
        ),
    ]
